# Generated by Django 5.0.3 on 2024-10-24 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GaleriaDePlanta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='')),
                ('descricao', models.CharField(max_length=100, verbose_name='')),
                ('imagem', models.CharField(max_length=100, verbose_name='')),
            ],
            options={
                'verbose_name': 'GaleriaDePlanta',
                'verbose_name_plural': 'GaleriDePlantas',
            },
        ),
        migrations.CreateModel(
            name='Orcamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='')),
                ('tipo', models.CharField(max_length=100, verbose_name='Tipo de planta')),
                ('dimensoes', models.CharField(max_length=100, verbose_name='Dimensões ultilizadas')),
                ('materiais', models.CharField(max_length=100, verbose_name='Materiais ultilizados')),
                ('descricao', models.CharField(max_length=100, verbose_name='Descrição sobre a planta')),
                ('preco', models.CharField(max_length=100, verbose_name='Valor da planta')),
            ],
            options={
                'verbose_name': 'Orcamento',
                'verbose_name_plural': 'Orcamentos',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='')),
                ('telefone', models.CharField(max_length=100, verbose_name='')),
                ('cidade', models.CharField(max_length=100, verbose_name='')),
                ('email', models.CharField(max_length=100, verbose_name='')),
                ('senha', models.CharField(max_length=100, verbose_name='')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
    ]
